site_name: WillyStation
site_url: http://willystation.com
theme:
  name: material
  features: 
   - navigation.tabs
   - navigation.selections
   - toc.integrate
   - navigation.top
   - navigation.indexes
   - search.suggest
   - search.highlight
   - content.tabs.link
   - content.code.annotation
   - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
nav:
  - Home: index.md
  - Getting Started:
    - Creating A Plex Account: Getting Started/Create A Plex Account.md
    - Initial Setup: Getting Started/Intial Setup.md
  - Requesting Movies & TV Shows:
    - Requesting Movies & TV Shows: Request Movies & Shows/Requesting Movies & Shows.md